[project]
name = "agents-sdk-mcp"
version = "0.1.0"
description = "Openai agents sdk cli project with Fast Mcp"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.17.0",
    "openai-agents>=0.3.3",
    "prompt-toolkit>=3.0.52",
    "uvicorn>=0.37.0",
]
